# Generated by Django 4.2.3 on 2023-07-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='opisanie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena')),
                ('auction', models.BooleanField(help_text='уместность торга', verbose_name='torg')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updateat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
